name: Build NAV appliance
on: [push, pull_request]

jobs:
  packer:
    name: "Build appliance using Packer"
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Template
        run: |
          packer validate buster.json
        env:
          PACKER_LOG: 0

      - name: Build Artifact
        run: |
          packer build buster.json
        env:
          PACKER_LOG: 0

      - name: Upload appliance artifacts
        uses: actions/upload-artifact@v2
        with:
          name: navappliance
          path: |
            navappliance/**/*
