name: Build NAV appliance
on: [push, pull_request]

jobs:
  packer:
    name: "Build appliance using Packer"
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Validate Template
        run: |
          packer validate buster.json
        env:
          PACKER_LOG: 0

      - name: Build Artifact
        run: |
          packer build buster.json
        env:
          PACKER_LOG: 0

      - name: Upload appliance artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "navappliance/**/*"
          name: latest
          body: "${{ steps.date.outputs.date }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
