name: Build NAV appliance
on: [push, pull_request, workflow_dispatch]

jobs:
  packer:
    name: "Build appliance using Packer"
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Template
        run: |
          packer validate bullseye.json
        env:
          PACKER_LOG: 0

      - name: Build Artifact
        run: |
          packer build bullseye.json
        env:
          PACKER_LOG: 0

      - name: Upload appliance artifact
        uses: actions/upload-artifact@v2
        with:
          name: navappliance
          path: |
            navappliance/**/*
